README.md, README_EN.md
=> docs: add English README

Cargo.lock, Cargo.toml, services/metadata/src/lib.rs, services/metadata/src/tests/mod.rs, services/metadata/src/types.rs, services/node_manager/Cargo.toml, services/node_manager/src/lib.rs, services/node_manager/src/tests/mod.rs, services/node_manager/src/tests/test_genesis.toml, services/node_manager/src/types.rs, src/main.rs
feat: add service
add node manager service to manage consensus node
Fixes #
=> add node manager service

services/riscv/src/vm/interpreter.rs, services/riscv/src/vm/syscall/assert.rs, services/riscv/src/vm/syscall/debug.rs
change
print debug and assert message to log
Fixes #
=> change: debug and assert syscall, print to log

Cargo.lock, Cargo.toml, services/asset/Cargo.toml, services/metadata/Cargo.toml, services/node_manager/Cargo.toml, services/riscv/Cargo.toml, src/main.rs
=> update to v0.0.1-rc.1

services/riscv/src/vm/interpreter.rs, tests/e2e/asset.test.ts, tests/e2e/jest.config.js, tests/e2e/jest.setup.js, tests/e2e/node_manager.test.ts, tests/e2e/riscv.test.ts, tests/e2e/utils.ts
=> fix: riscv invalid contract cause panic problem

docs/build/gql_api.sh, docs/graphql_api.md, docs/schema.graphql
Doc.
Update the api doc and the script generates the doc.
Fixes #
=> doc: update api doc

Cargo.lock, Cargo.toml, services/asset/Cargo.toml, services/asset/src/tests/mod.rs, services/metadata/Cargo.toml, services/metadata/src/tests/mod.rs, services/node_manager/Cargo.toml, services/node_manager/src/tests/mod.rs, services/riscv/Cargo.toml, services/riscv/src/tests/mod.rs
chore
update muta dependency
Fixes #
=> chore: update muta dependency

services/asset/src/lib.rs
fix
to support call asset service `transfer_from` method by contract
Fixes #
=> fix: call asset service transfer_from by contract

Cargo.lock, Cargo.toml, docs/faq.md, services/asset/Cargo.toml, services/metadata/Cargo.toml, services/node_manager/Cargo.toml, services/riscv/Cargo.toml, src/main.rs, tests/e2e/package-lock.json, tests/e2e/package.json
Chore.
- update version
- pass e2e test
Fixes #
=> chore: update version in main

config/chain.toml, config/genesis.toml
chore
update default configuration
Fixes #
=> chore: update default configuration

Cargo.lock, Cargo.toml, services/admission_control/Cargo.toml, services/admission_control/src/lib.rs, services/admission_control/src/tests.rs, services/admission_control/src/types.rs
feat
add admission control services
Fixes #
=> feat(service): add admission control services

services/asset/src/lib.rs, services/asset/src/tests/mod.rs
change
BREAKING CHANGE:
- remove TransferToSelf service error
Fixes #
=> change!(asset): allow transfer to self

.hooks/pre-commit
chore
add cargo fmt pre-commit hook
Fixes #
=> chore: add cargo fmt pre-commit hook

config/genesis.toml, services/riscv/src/authorization.rs, services/riscv/src/error.rs, services/riscv/src/lib.rs, services/riscv/src/tests/mod.rs, services/riscv/src/types.rs, tests/e2e/change_validators/templates/genesis.toml.template, tests/e2e/genesis.toml, tests/e2e/riscv.test.ts
feat
If authorization is enabled, a deployed contract must be approved
by an admin. Otherwise it's not executable.
BREAKING CHANGE:
- get_contract api now also return authorizer
- rename enable_whitelist to enable_authorization in genesis.toml
- rename whitelist to deploy_auth in genesis.toml
Fixes #
=> feat(riscv): contract authorization

services/riscv/src/lib.rs, services/riscv/src/vm/interpreter.rs, services/riscv/src/vm/mod.rs
change
Native rust version will nerve be used, remove it.
Also fixes #60.
Fixes #
=> change(riscv): remove unused slower NativeRust riscv machine

.travis.yml
Prepare for release through travis
chore
static link openssl on bionic box
Fixes #
=> chore(ci): static link openssl on bionic box

Cargo.lock, services/kyc/Cargo.toml, services/kyc/src/error.rs, services/kyc/src/expression/evaluation.rs, services/kyc/src/expression/mod.rs, services/kyc/src/expression/node.rs, services/kyc/src/expression/tests/mod.rs, services/kyc/src/expression/token.rs, services/kyc/src/expression/traits.rs, services/kyc/src/expression/types.rs, services/kyc/src/lib.rs, services/kyc/src/tests.rs, services/kyc/src/types.rs
feat
implement kyc service
Fixes #
=> feat(kyc): implement kyc service

services/asset/src/lib.rs, services/asset/src/tests/mod.rs, services/asset/src/types.rs
change
only asset holders can burn their property
Fixes #
=> change(asset): only asset holders can burn their property

services/governance/src/lib.rs, services/governance/src/tests/mod.rs
fix
accumulated profits aren't reset
Fixes #
=> fix(governance): accumulated profits aren't reset after tx

services/asset/src/lib.rs
This logic is implement in Governance service now.
change
remove unused fee charge in tx_hook_before
Fixes #
=> change(asset): remove unused fee charge in tx_hook_before

config/genesis.toml, services/admission_control/src/lib.rs, services/admission_control/src/tests.rs
change
change is_blocked to is_permitted
Fixes #
=> change(admission control): is_blocked to is_permitted

config/genesis.toml
fix
outdated genesis.toml
Fixes #
=> fix(genesis): panic on governance genesis initialization

config/genesis.toml, services/admission_control/src/lib.rs, services/admission_control/src/tests.rs, services/admission_control/src/types.rs
feat
check tx sender balance against failure fee
Fixes #
=> feat(admission control): check tx sender balance against failure fee

Cargo.lock, Cargo.toml, services/admission_control/Cargo.toml, services/asset/Cargo.toml, services/governance/Cargo.toml, services/governance/src/lib.rs, services/kyc/Cargo.toml, services/metadata/Cargo.toml, services/riscv/Cargo.toml
chore
bump to muta v0.2.0-dev.0
Fixes #
=> chore: bump to muta v0.2.0-dev.0

docs/sidebar.md
=> docs: update sidebar

docs/config.md
=> docs: update-config

docs/config.md
=> docs: Update config.md

Cargo.lock, Cargo.toml, services/admission_control/Cargo.toml, services/asset/Cargo.toml, services/governance/Cargo.toml, services/kyc/Cargo.toml, services/metadata/Cargo.toml, services/riscv/Cargo.toml
=> chore: bump muta to latest tag

config/genesis.toml, devtools/docker-compose/node-genesis.toml, services/governance/src/tests/test_genesis.toml, tests/e2e/change_validators/templates/genesis.toml.template, tests/e2e/genesis.toml, tests/integration/test_genesis.toml
chore
add ```bech32_address_hrp``` to genesis.toml
Fixes #
=> chore: add bech32_address_hrp to genesis.toml

services/asset/src/lib.rs, services/asset/src/types.rs, services/riscv/src/vm/chain_interface.rs
fix: asset service verify bugs, riscv sub overflow bug #129
Slow mist found these bugs, we fix it.
=> fix: asset service verify bugs, riscv sub overflow bug
